FROM                python:3.6.5-slim
MAINTAINER          rlaalsrbgk@gmail.com

# pip install uwsgi
RUN                 apt -y update && apt -y dist-upgrade
RUN                 apt -y install build-essential
RUN                 apt -y install nginx supervisor

COPY                ./requirements.txt  /srv/
RUN                 pip install --upgrade pip
RUN                 pip install -r /srv/requirements.txt