# Generated by Django 2.1.2 on 2018-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('detail', models.CharField(max_length=300)),
                ('accessory', models.ManyToManyField(related_name='accessory_skills', to='items.Accessory')),
                ('armor', models.ManyToManyField(related_name='armor_skill', to='armor.Armor')),
            ],
        ),
    ]
