# Generated by Django 2.1.2 on 2018-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='detail',
            new_name='Lv1',
        ),
        migrations.AddField(
            model_name='skill',
            name='Lv2',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='Lv3',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='Lv4',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='Lv5',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
