# Generated by Django 2.1.2 on 2018-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20181020_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='Lv2',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv3',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv4',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv5',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
