# Generated by Django 2.1.2 on 2018-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20181020_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='Lv1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Lv5',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
