# Generated by Django 2.1.3 on 2018-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181105_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_check',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
