# Generated by Django 2.1.2 on 2018-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equip_region', models.CharField(max_length=100)),
                ('rare', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('vs_fire', models.IntegerField()),
                ('vs_water', models.IntegerField()),
                ('vs_thunder', models.IntegerField()),
                ('vs_ice', models.IntegerField()),
                ('vs_dragon', models.IntegerField()),
                ('slot', models.CharField(max_length=50)),
            ],
        ),
    ]
