# Generated by Django 2.1.2 on 2018-10-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='slot',
        ),
    ]
