# Generated by Django 2.1.2 on 2018-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0002_remove_armor_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='slot',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
