# Generated by Django 2.1.1 on 2018-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0010_lightbowgun'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyBowgun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rare', models.IntegerField()),
                ('produce', models.CharField(max_length=100)),
                ('attack', models.IntegerField()),
                ('recoil', models.CharField(max_length=50)),
                ('fatal_blow', models.IntegerField()),
                ('slot', models.CharField(max_length=100)),
                ('custom_mod', models.CharField(max_length=50)),
                ('special_ammo', models.CharField(max_length=200)),
            ],
        ),
    ]
