# Generated by Django 2.1.2 on 2018-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='armor',
            field=models.ManyToManyField(related_name='makes_armor', to='armor.Armor'),
        ),
        migrations.AlterField(
            model_name='items',
            name='charge_blade',
            field=models.ManyToManyField(related_name='makes_charge_blade', to='weapon.ChargeBlade'),
        ),
        migrations.AlterField(
            model_name='items',
            name='great_sword',
            field=models.ManyToManyField(related_name='makes_great_sword', to='weapon.GreatSword'),
        ),
        migrations.AlterField(
            model_name='items',
            name='gun_lance',
            field=models.ManyToManyField(related_name='makes_gun_lance', to='weapon.GunLance'),
        ),
        migrations.AlterField(
            model_name='items',
            name='hammer',
            field=models.ManyToManyField(related_name='makes_hammer', to='weapon.Hammer'),
        ),
        migrations.AlterField(
            model_name='items',
            name='heavy_bowgun',
            field=models.ManyToManyField(related_name='makes_heavy_bowgun', to='weapon.HeavyBowgun'),
        ),
        migrations.AlterField(
            model_name='items',
            name='lance',
            field=models.ManyToManyField(related_name='makes_lance', to='weapon.Lance'),
        ),
        migrations.AlterField(
            model_name='items',
            name='light_bowgun',
            field=models.ManyToManyField(related_name='makes_light_bowgun', to='weapon.LightBowgun'),
        ),
        migrations.AlterField(
            model_name='items',
            name='long_sword',
            field=models.ManyToManyField(related_name='makes_long_sword', to='weapon.LongSword'),
        ),
        migrations.AlterField(
            model_name='items',
            name='one_hand_sword',
            field=models.ManyToManyField(related_name='makes_one_hand_sword', to='weapon.OneHandSword'),
        ),
        migrations.AlterField(
            model_name='items',
            name='switch_axe',
            field=models.ManyToManyField(related_name='makes_switch_axe', to='weapon.SwitchAxe'),
        ),
        migrations.AlterField(
            model_name='items',
            name='two_sowrds',
            field=models.ManyToManyField(related_name='makes_two_swords', to='weapon.TwoSwords'),
        ),
    ]
